;;; island-theme.el --- Material You theme generated by matugen -*- lexical-binding: t; -*-
;;
;; Author: Vladislav <nikko@cachyos-x8664>
;; Homepage: https://github.com/nikko/iris-theme
;; Package-Requires: ((emacs "24.3") (doom-themes "2.2.1"))
;;
;; This file is not part of GNU Emacs.
;;
;;; Commentary:
;;
;;  Generated file — do not edit.  The source template lives in
;;  the shell's Templates/Matugen/emacs.el and is rendered by matugen on every
;;  wallpaper change.  Colors come from the Material You scheme derived from
;;  the current wallpaper: surfaces and accents are the Material roles, while
;;  red/green/yellow/... are the harmonized custom colors declared in
;;  the shell's Templates/matugen-base.toml.
;;
;;; Code:

(require 'doom-themes)

(defgroup island-theme nil
  "Options for the matugen theme."
  :group 'doom-themes)

(def-doom-theme island
  "A Material You theme generated from the current wallpaper by matugen."

  ;;;; Color palette
  ;; name        gui                                                    256 16
  ((bg          '("#101417"                       nil nil))
   (bg-alt      '("#1c2024"             nil nil))
   (fg          '("#e0e3e8"                    nil nil))
   (fg-alt      '("#c1c7ce"            nil nil))

   ;; base0 is the "darkest" end, base8 the "lightest" (inverted in light
   ;; mode, which doom tolerates).
   (base0       '("#0b0f12"      nil nil))
   (base1       '("#181c20"         nil nil))
   (base2       '("#1c2024"             nil nil))
   (base3       '("#262a2e"        nil nil))
   (base4       '("#313539"     nil nil))
   (base5       '("#41474d"               nil nil))
   (base6       '("#8b9198"                       nil nil))
   (base7       '("#c1c7ce"            nil nil))
   (base8       '("#e0e3e8"                    nil nil))

   (grey        base6)
   (red         '("#ffb1c0"                           nil nil))
   (orange      '("#ffb693"                        nil nil))
   (green       '("#91d5ad"                         nil nil))
   (teal        '("#81d3df"                          nil nil))
   (yellow      '("#cbcb76"                        nil nil))
   (blue        '("#9dcbfc"                          nil nil))
   (dark-blue   '("#97ccf8"             nil nil))
   (magenta     '("#dcb9f8"                       nil nil))
   (violet      '("#d0bfe8"                      nil nil))
   (cyan        '("#81d3df"                          nil nil))
   (dark-cyan   '("#b8c8d9"                     nil nil))

   ;;;; Face categories — driven by the Material roles so the syntax colors
   ;;;; stay in the same tonal family as the rest of the desktop.
   (highlight      '("#97ccf8"                    nil nil))
   (vertical-bar   base2)
   (selection      base2)
   (builtin        '("#d0bfe8"                   nil nil))
   (comments       '("#8b9198"                    nil nil))
   (doc-comments   '("#c1c7ce"         nil nil))
   (constants      '("#ffb693"                     nil nil))
   (functions      '("#d0bfe8"                   nil nil))
   (keywords       '("#97ccf8"                    nil nil))
   (methods        '("#d0bfe8"                   nil nil))
   (operators      '("#c1c7ce"         nil nil))
   (type           '("#b8c8d9"                  nil nil))
   (strings        '("#91d5ad"                      nil nil))
   (variables      '("#e0e3e8"                 nil nil))
   (numbers        '("#ffb693"                     nil nil))
   (region         base2)
   (error          '("#ffb4ab"                      nil nil))
   (warning        yellow)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

   ;;;; Custom
   (modeline-bg     bg-alt)
   (modeline-bg-alt bg)
   (modeline-fg     fg)
   (modeline-fg-alt fg-alt))

  ;;;; Face overrides
  (((line-number              &override) :foreground base6)
   ((line-number-current-line &override) :foreground highlight :weight 'bold)
   (cursor  :background highlight)
   (mode-line          :background modeline-bg     :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-alt :foreground modeline-fg-alt)
   ((font-lock-comment-face &override) :slant 'italic)
   (doom-modeline-bar :background highlight)
   (tooltip :background bg-alt :foreground fg)

   ;;;; Selection — the container tones sit close to bg, so these are
   ;;;; blended off the accent instead.
   (region  :background (doom-blend highlight bg 0.15) :extend t)
   (hl-line :background (doom-blend fg bg 0.07))
   (vertico-current :background (doom-blend highlight bg 0.22)
                    :foreground fg :extend t)
   (vertico-group-title :foreground highlight :weight 'bold)

   ;;;; Match highlighting
   ((completions-common-part &override) :foreground highlight :weight 'bold)
   (orderless-match-face-0 :foreground highlight :weight 'bold)
   (orderless-match-face-1 :foreground magenta   :weight 'bold)
   (orderless-match-face-2 :foreground green     :weight 'bold)
   (orderless-match-face-3 :foreground yellow    :weight 'bold))

  ;;;; Variable overrides
  ())

(provide-theme 'island)
;;; island-theme.el ends here
