;;; island-theme.el --- Material You theme generated by matugen -*- lexical-binding: t; -*-
;;
;; Author: Vladislav <nikko@cachyos-x8664>
;; Homepage: https://github.com/nikko/iris-theme
;; Package-Requires: ((emacs "24.3") (doom-themes "2.2.1"))
;;
;; This file is not part of GNU Emacs.
;;
;;; Commentary:
;;
;;  Generated file — do not edit.  The source template lives in
;;  the shell's Templates/Matugen/emacs.el and is rendered by matugen on every
;;  wallpaper change.  Colors come from the Material You scheme derived from
;;  the current wallpaper: surfaces and accents are the Material roles, while
;;  red/green/yellow/... are the harmonized custom colors declared in
;;  the shell's Templates/matugen-base.toml.
;;
;;; Code:

(require 'doom-themes)

(defgroup island-theme nil
  "Options for the matugen theme."
  :group 'doom-themes)

(def-doom-theme island
  "A Material You theme generated from the current wallpaper by matugen."

  ;;;; Color palette
  ;; name        gui                                                    256 16
  ((bg          '("#1a1110"                       nil nil))
   (bg-alt      '("#271d1c"             nil nil))
   (fg          '("#f1dedc"                    nil nil))
   (fg-alt      '("#d8c2be"            nil nil))

   ;; base0 is the "darkest" end, base8 the "lightest" (inverted in light
   ;; mode, which doom tolerates).
   (base0       '("#140c0b"      nil nil))
   (base1       '("#231918"         nil nil))
   (base2       '("#271d1c"             nil nil))
   (base3       '("#322826"        nil nil))
   (base4       '("#3d3231"     nil nil))
   (base5       '("#534341"               nil nil))
   (base6       '("#a08c89"                       nil nil))
   (base7       '("#d8c2be"            nil nil))
   (base8       '("#f1dedc"                    nil nil))

   (grey        base6)
   (red         '("#ffb3ac"                           nil nil))
   (orange      '("#ffb693"                        nil nil))
   (green       '("#b1d18a"                         nil nil))
   (teal        '("#85d6c0"                          nil nil))
   (yellow      '("#eebf6d"                        nil nil))
   (blue        '("#b5c4ff"                          nil nil))
   (dark-blue   '("#ffb4aa"             nil nil))
   (magenta     '("#f7b2df"                       nil nil))
   (violet      '("#dfc38c"                      nil nil))
   (cyan        '("#85d6c0"                          nil nil))
   (dark-cyan   '("#e7bdb7"                     nil nil))

   ;;;; Face categories — driven by the Material roles so the syntax colors
   ;;;; stay in the same tonal family as the rest of the desktop.
   (highlight      '("#ffb4aa"                    nil nil))
   (vertical-bar   base2)
   (selection      base2)
   (builtin        '("#dfc38c"                   nil nil))
   (comments       '("#a08c89"                    nil nil))
   (doc-comments   '("#d8c2be"         nil nil))
   (constants      '("#ffb693"                     nil nil))
   (functions      '("#dfc38c"                   nil nil))
   (keywords       '("#ffb4aa"                    nil nil))
   (methods        '("#dfc38c"                   nil nil))
   (operators      '("#d8c2be"         nil nil))
   (type           '("#e7bdb7"                  nil nil))
   (strings        '("#b1d18a"                      nil nil))
   (variables      '("#f1dedc"                 nil nil))
   (numbers        '("#ffb693"                     nil nil))
   (region         base2)
   (error          '("#ffb4ab"                      nil nil))
   (warning        yellow)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

   ;;;; Custom
   (modeline-bg     bg-alt)
   (modeline-bg-alt bg)
   (modeline-fg     fg)
   (modeline-fg-alt fg-alt))

  ;;;; Face overrides
  (((line-number              &override) :foreground base6)
   ((line-number-current-line &override) :foreground highlight :weight 'bold)
   (cursor  :background highlight)
   (mode-line          :background modeline-bg     :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-alt :foreground modeline-fg-alt)
   ((font-lock-comment-face &override) :slant 'italic)
   (doom-modeline-bar :background highlight)
   (tooltip :background bg-alt :foreground fg)

   ;;;; Selection — the container tones sit close to bg, so these are
   ;;;; blended off the accent instead.
   (region  :background (doom-blend highlight bg 0.15) :extend t)
   (hl-line :background (doom-blend fg bg 0.07))
   (vertico-current :background (doom-blend highlight bg 0.22)
                    :foreground fg :extend t)
   (vertico-group-title :foreground highlight :weight 'bold)

   ;;;; Match highlighting
   ((completions-common-part &override) :foreground highlight :weight 'bold)
   (orderless-match-face-0 :foreground highlight :weight 'bold)
   (orderless-match-face-1 :foreground magenta   :weight 'bold)
   (orderless-match-face-2 :foreground green     :weight 'bold)
   (orderless-match-face-3 :foreground yellow    :weight 'bold))

  ;;;; Variable overrides
  ())

(provide-theme 'island)
;;; island-theme.el ends here
