;;; matugen-theme.el --- Material You theme generated by matugen -*- lexical-binding: t; -*-
;;
;; Author: Vladislav <nikko@cachyos-x8664>
;; Homepage: https://github.com/nikko/iris-theme
;; Package-Requires: ((emacs "24.3") (doom-themes "2.2.1"))
;;
;; This file is not part of GNU Emacs.
;;
;;; Commentary:
;;
;;  Generated file — do not edit.  The source template lives in
;;  ~/.config/matugen/matugen-theme.el and is rendered by matugen on every
;;  wallpaper change.  Colors come from the Material You scheme derived from
;;  the current wallpaper: surfaces and accents are the Material roles, while
;;  red/green/yellow/... are the harmonized custom colors declared in
;;  ~/.config/matugen/config.toml.
;;
;;; Code:

(require 'doom-themes)

(defgroup matugen-theme nil
  "Options for the matugen theme."
  :group 'doom-themes)

(def-doom-theme matugen
  "A Material You theme generated from the current wallpaper by matugen."

  ;;;; Color palette
  ;; name        gui                                                    256 16
  ((bg          '("#191114"                       nil nil))
   (bg-alt      '("#261d20"             nil nil))
   (fg          '("#efdfe2"                    nil nil))
   (fg-alt      '("#d5c2c6"            nil nil))

   ;; base0 is the "darkest" end, base8 the "lightest" (inverted in light
   ;; mode, which doom tolerates).
   (base0       '("#130c0e"      nil nil))
   (base1       '("#22191c"         nil nil))
   (base2       '("#261d20"             nil nil))
   (base3       '("#31282a"        nil nil))
   (base4       '("#3c3235"     nil nil))
   (base5       '("#514347"               nil nil))
   (base6       '("#9e8c91"                       nil nil))
   (base7       '("#d5c2c6"            nil nil))
   (base8       '("#efdfe2"                    nil nil))

   (grey        base6)
   (red         '("#ffb2bc"                           nil nil))
   (orange      '("#ffb693"                        nil nil))
   (green       '("#b1d18a"                         nil nil))
   (teal        '("#81d3df"                          nil nil))
   (yellow      '("#eebf6d"                        nil nil))
   (blue        '("#b5c4ff"                          nil nil))
   (dark-blue   '("#ffb0cb"             nil nil))
   (magenta     '("#f7b2df"                       nil nil))
   (violet      '("#f0bc95"                      nil nil))
   (cyan        '("#81d3df"                          nil nil))
   (dark-cyan   '("#e2bdc7"                     nil nil))

   ;;;; Face categories — driven by the Material roles so the syntax colors
   ;;;; stay in the same tonal family as the rest of the desktop.
   (highlight      '("#ffb0cb"                    nil nil))
   (vertical-bar   base2)
   (selection      base2)
   (builtin        '("#f0bc95"                   nil nil))
   (comments       '("#9e8c91"                    nil nil))
   (doc-comments   '("#d5c2c6"         nil nil))
   (constants      '("#ffb693"                     nil nil))
   (functions      '("#f0bc95"                   nil nil))
   (keywords       '("#ffb0cb"                    nil nil))
   (methods        '("#f0bc95"                   nil nil))
   (operators      '("#d5c2c6"         nil nil))
   (type           '("#e2bdc7"                  nil nil))
   (strings        '("#b1d18a"                      nil nil))
   (variables      '("#efdfe2"                 nil nil))
   (numbers        '("#ffb693"                     nil nil))
   (region         base2)
   (error          '("#ffb4ab"                      nil nil))
   (warning        yellow)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

   ;;;; Custom
   (modeline-bg     bg-alt)
   (modeline-bg-alt bg)
   (modeline-fg     fg)
   (modeline-fg-alt fg-alt))

  ;;;; Face overrides
  (((line-number              &override) :foreground base6)
   ((line-number-current-line &override) :foreground highlight :weight 'bold)
   (cursor  :background highlight)
   (mode-line          :background modeline-bg     :foreground modeline-fg)
   (mode-line-inactive :background modeline-bg-alt :foreground modeline-fg-alt)
   ((font-lock-comment-face &override) :slant 'italic)
   (doom-modeline-bar :background highlight)
   (tooltip :background bg-alt :foreground fg)

   ;;;; Selection — the container tones sit close to bg, so these are
   ;;;; blended off the accent instead.
   (region  :background (doom-blend highlight bg 0.15) :extend t)
   (hl-line :background (doom-blend fg bg 0.07))
   (vertico-current :background (doom-blend highlight bg 0.22)
                    :foreground fg :extend t)
   (vertico-group-title :foreground highlight :weight 'bold)

   ;;;; Match highlighting
   ((completions-common-part &override) :foreground highlight :weight 'bold)
   (orderless-match-face-0 :foreground highlight :weight 'bold)
   (orderless-match-face-1 :foreground magenta   :weight 'bold)
   (orderless-match-face-2 :foreground green     :weight 'bold)
   (orderless-match-face-3 :foreground yellow    :weight 'bold))

  ;;;; Variable overrides
  ())

(provide-theme 'matugen)
;;; matugen-theme.el ends here
